variables:
  CI_SERVER_URL: "http://gitlab"
  GIT_STRATEGY: clone

test-job:
  stage: build
  image: alpine:latest
  script:
    - echo "Победа! Раннер на Mac M1 увидел проект."
    - echo "Задание выполнено успешно."

